### ISSUE TITLE
Feature Requests: Hide "duplicate page" and "Show children as list" from "right click menu"

### ISSUE THREAD

**Issue by jacobsjensen** [axllent/silverstripe-cms-tweaks#4]
Hi, first off this is not an issue, but a feature request to make this heavenly tweak-bundle even better:

Both feature request are concerning the "right click menu" on the SiteTree menu.
1. 
   Hide "duplicate page" to users without `SITETREE_REORGANISE` permissions  
   2.
   Hide "Show children as list" when a page has no children

This would make it even less confusing to those non-administrative tied-on-hand-an-feet users :-)

**Comment by axllent** [comment]
Thanks for the suggestion, great catch! By the way, what version of SilverStripe are you running, as the following update is for 3.3 only? I don't tend to focus on backwards compatibility, but if you need 3.2 I can probably sort something out.
1. I have created a fix for the "duplicate page" content menu for users without the `SITETREE_REORGANISE` permissions (plus another couple of bug fixes) - [see release for SS 3.3](https://github.com/axllent/silverstripe-cms-tweaks/releases/tag/1.2.1).
2. Unfortunately the "Show children as list" isn't quite what one would expect. The content menu "Show children as list" is generated in `CMSMail.Tree.js` based on whether a page type **can have** children or not, and not whether it has children or not (I was about to submit a bug report and patch when I realised this as it didn't make sense to me either). I believe it is intended to allow easy editing of a "subsection" of pages, adding new pages and also _editing_ of those pages. I understand why you would like this, however it isn't possible to implement without changing how the content menu is generated on right-click, which in turn would remove the functionality it was intended to have for all users.

I totally understand your suggestion, but I don't think it is possible without a serious hack (and serious hacks tend to break with CMS updates) :-)

**Comment by axllent** [comment]
I just added a release for SilverStripe 3.2 too (turns out I needed it too) ;-)
