### ISSUE TITLE
Typo inside the code

### ISSUE THREAD

**Issue by mychaelo** [axllent/silverstripe-cms-tweaks#5]
Reports page in Silverstripe CMS Admin will not work because of a typo in your code.

> Warning: count(): Parameter must be an array or an object that implements Countable in
> /var/www/ss/vendor/axllent/silverstripe-cms-tweaks/src/CMSTweaks.php
> on line 109

Offending line:
```php
if (count($timestamped_css > 0)) {
```

Which probably should be:
```php
if (count($timestamped_css) > 0) {
```

@axllent

**Comment by axllent** [comment]
Thanks @mychaelo ! Well spotted... I've just released a new version to fix this.
