### ISSUE TITLE
extended_valid_elements overriding defaults

### ISSUE THREAD

**Issue by korthjp17** [axllent/silverstripe-cms-tweaks#6]
https://github.com/axllent/silverstripe-cms-tweaks/blob/66de39757db93bb1988195e7a2c1e5b5ea3f7e5d/src/CMSTweaks.php#L81-L87

The `extended_valid_elements` option is currently overriding the defaults instead of appending them.

**Comment by axllent** [comment]
Many thanks @korthjp17 - I'll get this merged in and released now.

**Comment by korthjp17** [comment]
You're welcome!

@axllent Is there a reason `div` is set as an invalid_element? We are running into a case where we need to use divs in a project and we were going to figure out a workaround to override it after this one is set.

**Comment by axllent** [comment]
I have never experienced a situation where a `div` was useful inside of TinyMCE, and in many cases experienced stray divs being inserted via copy & paste (blame the client, but still). 

One solution here would be for me to change `invalid_elements` and `extended_valid_elements` to static variables so that they could be overwritten via a yaml config.

Out of curiosity, how are you managing to work with divs within TinyMCE anyway?

**Comment by korthjp17** [comment]
I'd say 99% of the time I would agree with you, especially having clients copy/paste into the CMS and getting a ton of code they didn't even know would come with it.

We are working on moving a site from a different platform to SS and moving a lot of static elements from the old system into blocks. So for example, one section was an accordion built all static in the template, but we are moving it into an accordion block so it's editable in the CMS, but they had some extra divs and things for placement and styling inside of that panel.

I think your idea of moving them to static variables and editable via yaml config would be a good solution. the `extended_valid_elements` wouldn't necessarily need to change because now that it's getting the existing options that are set first and appending new options, it can already be configured in the `_config.php`.

**Comment by axllent** [comment]
My apologies, but I think I'm actually going to revert my last update. The whole point I overwrote `extended_valid_elements` in the first place was that the default config allows more "features" than I like (ie: related crap from copy/paste):

`img[class|src|alt|title|hspace|vspace|width|height|align|name|usemap|data*],iframe[src|name|width|height|align|frameborder|marginwidth|marginheight|scrolling],object[width|height|data|type],param[name|value],map[class|name|id],area[shape|coords|href|target|alt]`

In keeping consistency, my plan is to add both `invalid_elements` and `extended_valid_elements` as static variables (defaulting to the values I initially had). These will not get appended to anything, simply used to set them. This way you can overwrite them manually for that one project, so if you want the original HtmlEditorConfig + and others then you can just set that in the yaml.

Will that work for you?

**Comment by korthjp17** [comment]
Yeah, I think that will work. Completely understand the point of copy/paste coming over when clients enter content. I think the only other one that we've been missing on a few projects now is not being able to use iframes as well.

But, I think doing them as static variables would be a good solution so they would be editable.

**Comment by axllent** [comment]
@korthjp17 I've just released a new version - so would you mind testing when you get a chance and confirm this caters for what you are needing? Thanks.

**Comment by korthjp17** [comment]
Yup, I’ll check it in the morning! Thanks for the help and adjusting the module! We use it on every project!

**Comment by korthjp17** [comment]
I tested it out this morning and everything is working great!! thanks for helping out and doing it so quick!

**Comment by axllent** [comment]
You are welcome, and thank you for your patch and info too.
