### ISSUE TITLE
URL Segment and related fields being removed on custom page type

### ISSUE THREAD

**Issue by MatMorrisParker** [axllent/silverstripe-cms-tweaks#8]
We have a site where you can only create one of some page types (e.g. staff list).

With this module installed on SS 5.2, it seems to remove the URL Segment and related fields from the CMS, when I don't believe this is correct (although if the logic behind it is correct, then happy to be told so).

It seems that a check is performed to see if the parent doesn't exist (it wouldn't in this case, as it's a top level page), and if you can't create a page of this type (which you can't because you can only have one), then the URL can't be changed.

https://github.com/axllent/silverstripe-cms-tweaks/blob/b9ebed550b88af442e1af32df1ee92f4aa056afd/src/MetadataTab.php#L133

Is this intended? If not, I'm happy to try and come up with a solution if I can understand the logic behind it.

In the (likely) case of it being me that's not understanding it correctly, happy to be corrected, too.

**Comment by axllent** [comment]
Hi @MatMorrisParker.

The reasoning behind that part of the module was to remove the ability to change the structure of these pages for people without permissions to add pages (ie: aimed at non-technical people). Unless I am misunderstanding your question, I'd say this logic is intended and working correctly. Basically if you have the permission to add a page, then you can modify the URLSegment, otherwise not.

Did I miss your point?

**Comment by MatMorrisParker** [comment]
Thanks for the response @axllent! I understand your point. In this test case, however, I was the administrator and have the option to add, edit and remove pages.

The code on the page that's having the issue is as follows -
```
	/**
	 * Returns true/false on whether this page can be created.
	 * Only one staff page is permitted.
	 *
	 * @param null $member
	 * @param array $context
	 * 
	 * @return bool
	 */
	public function canCreate($member = null, $context = []): bool
	{
		$staffPages 	= self::get();

		return !($staffPages->Count() > 0);
	}
```

This causes the URL Segment field to be hidden as the line I linked in my previous post returns **false**.

Perhaps an issue with _my_ logic here rather than the addon?

**Comment by axllent** [comment]
It could be your logic, depending on what you intend your `canCreate()` to return. What your function basically says is return true if there are no staffPages. Your logic is a little cryptic, so it's probably easier read as:

```php
	public function canCreate($member = null, $context = []): bool
	{
		return !self::get()->count();
	}
```

But is this really what you are trying to achieve here in this function?

**Comment by MatMorrisParker** [comment]
How strange! That does indeed fix the issue. Apologies for raising this, but really appreciate the speedy response.
